Get forecasts for only registered sensors
SeitaBV/flexmeasures-openweathermap pull request #13
Opened 2023-07-20 20:10 UTC by Ahmad-Wahid

Before we are considering all the sensors that we have `mapping`, but this limits us in terms of getting forecasts for only one or two sensors. In this PR, I have put a check on sensors means in case a sensor is not registered then it will be ignored.

2023-07-21 09:05 UTC, nhoening requested changes

2023-07-21 09:05 UTC, nhoening commented on flexmeasures_openweathermap/utils/owm.py
> +                        if weather_sensor not in db_forecasts.keys():
Let's add a log here that we found this particular sensor.: "Found pre-configured weather sensor {weather_sensor.name} ..."

2023-07-25 10:02 UTC, nhoening requested changes
This is a little mit more tricky than I had thought, but we're getting closer  :)

I even made two new tickets while thinking about this PR.

Here is one other comment I have - an different improvement I saw while looking at the code:

The line owm.py:107 (`data_source = get_or_create_owm_data_source()`) can move one upwards, outside of the for-loop (we use the same data source for all sensors).

2023-07-25 11:22 UTC, Ahmad-Wahid commented on flexmeasures_openweathermap/utils/owm.py
> +        current_app.logger.warning(
We already have `sensor_name` in the message. Or is it different?

2023-07-25 11:40 UTC, nhoening commented on flexmeasures_openweathermap/utils/owm.py
> +        current_app.logger.warning(
Yes agreed on that.

2023-07-26 11:12 UTC, merged